// Generated from: tests\UI\feature\login.feature
import { test } from "../../../../tests/UI/fixture/Fixtures.ts";

test.describe('User Authentication', () => {

  test.beforeEach('Background', async ({ Given, page }, testInfo) => { if (testInfo.error) return;
    await Given('I navigate to the Url "https://dev-dashboard-boneplus.b1automation.com"', null, { page }); 
  });
  
  test('Successful Login with Valid Credentials', { tag: ['@smoke'] }, async ({ When, Then, And, LoginPage, page }) => { 
    await And('I enter the email "gangadhar@blazeautomation.com"', null, { LoginPage }); 
    await And('Click on submit button', null, { LoginPage }); 
    await And('I enter the password "Blaze#43215"', null, { LoginPage }); 
    await When('Click on the Submit button', null, { LoginPage }); 
    await Then('That should redirect to the Dashboard "/dashboard/"', null, { page }); 
  });

  test.describe('Verify frontend validation for invalid email formats', () => {

    test('Example #1', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "usergmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #2', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "test.email.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #3', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #4', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "@domain.org"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #5', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user@"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #6', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "test@"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #7', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user@gmail"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #8', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "test@yahoo"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #9', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user@@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #10', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "test@domain@company.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #11', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user name@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #12', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "test@ gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #13', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user#gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #14', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "name$domain.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #15', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email ".user@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #16', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user.@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #17', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user..name@gmail.com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #18', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "user@gmail..com"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #19', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "@@@@@"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #20', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "....."', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

    test('Example #21', async ({ When, Then, And, LoginPage }) => { 
      await And('I enter the email "678909890"', null, { LoginPage }); 
      await When('Click on submit button', null, { LoginPage }); 
      await Then('I should see an error message indicating "Please enter a valid E-mail address"'); 
    });

  });

  test('Login with Incorrect Password', async ({ When, Then, And, LoginPage }) => { 
    await And('I enter the email "gangadhar@blazeautomation.com"', null, { LoginPage }); 
    await And('Click on submit button', null, { LoginPage }); 
    await And('I enter the password "123fthu"', null, { LoginPage }); 
    await When('Click on the Submit button', null, { LoginPage }); 
    await Then('I should see an error message indicating "Wrong password. Try again or click Forgot password to reset it."'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\UI\\feature\\login.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":34,"tags":["@smoke"],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"And I enter the email \"gangadhar@blazeautomation.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"gangadhar@blazeautomation.com\"","children":[{"start":19,"value":"gangadhar@blazeautomation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":37,"keywordType":"Context","textWithKeyword":"And Click on submit button","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"And I enter the password \"Blaze#43215\"","stepMatchArguments":[{"group":{"start":21,"value":"\"Blaze#43215\"","children":[{"start":22,"value":"Blaze#43215","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When Click on the Submit button","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then That should redirect to the Dashboard \"/dashboard/\"","stepMatchArguments":[{"group":{"start":38,"value":"\"/dashboard/\"","children":[{"start":39,"value":"/dashboard/","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":20,"pickleLine":50,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"usergmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"usergmail.com\"","children":[{"start":19,"value":"usergmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":26,"pickleLine":51,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"test.email.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"test.email.com\"","children":[{"start":19,"value":"test.email.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":32,"pickleLine":52,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"@gmail.com\"","children":[{"start":19,"value":"@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":38,"pickleLine":53,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"@domain.org\"","stepMatchArguments":[{"group":{"start":18,"value":"\"@domain.org\"","children":[{"start":19,"value":"@domain.org","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":44,"pickleLine":54,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user@\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user@\"","children":[{"start":19,"value":"user@","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":50,"pickleLine":55,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"test@\"","stepMatchArguments":[{"group":{"start":18,"value":"\"test@\"","children":[{"start":19,"value":"test@","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":56,"pickleLine":56,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user@gmail\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user@gmail\"","children":[{"start":19,"value":"user@gmail","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":62,"pickleLine":57,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"test@yahoo\"","stepMatchArguments":[{"group":{"start":18,"value":"\"test@yahoo\"","children":[{"start":19,"value":"test@yahoo","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":68,"pickleLine":58,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user@@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user@@gmail.com\"","children":[{"start":19,"value":"user@@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":74,"pickleLine":59,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"test@domain@company.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"test@domain@company.com\"","children":[{"start":19,"value":"test@domain@company.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":80,"pickleLine":60,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user name@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user name@gmail.com\"","children":[{"start":19,"value":"user name@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":86,"pickleLine":61,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"test@ gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"test@ gmail.com\"","children":[{"start":19,"value":"test@ gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":92,"pickleLine":62,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user#gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user#gmail.com\"","children":[{"start":19,"value":"user#gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":63,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"name$domain.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"name$domain.com\"","children":[{"start":19,"value":"name$domain.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":104,"pickleLine":64,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \".user@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\".user@gmail.com\"","children":[{"start":19,"value":".user@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":110,"pickleLine":65,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user.@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user.@gmail.com\"","children":[{"start":19,"value":"user.@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":116,"pickleLine":66,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":117,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user..name@gmail.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user..name@gmail.com\"","children":[{"start":19,"value":"user..name@gmail.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":122,"pickleLine":67,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":123,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"user@gmail..com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"user@gmail..com\"","children":[{"start":19,"value":"user@gmail..com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":128,"pickleLine":68,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"@@@@@\"","stepMatchArguments":[{"group":{"start":18,"value":"\"@@@@@\"","children":[{"start":19,"value":"@@@@@","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":131,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":134,"pickleLine":69,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":135,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \".....\"","stepMatchArguments":[{"group":{"start":18,"value":"\".....\"","children":[{"start":19,"value":".....","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":137,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":140,"pickleLine":70,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I enter the email \"678909890\"","stepMatchArguments":[{"group":{"start":18,"value":"\"678909890\"","children":[{"start":19,"value":"678909890","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":142,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When Click on submit button","stepMatchArguments":[]},{"pwStepLine":143,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Please enter a valid E-mail address\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Please enter a valid E-mail address\"","children":[{"start":42,"value":"Please enter a valid E-mail address","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":148,"pickleLine":72,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I navigate to the Url \"https://dev-dashboard-boneplus.b1automation.com\"","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"https://dev-dashboard-boneplus.b1automation.com\"","children":[{"start":23,"value":"https://dev-dashboard-boneplus.b1automation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":149,"gherkinStepLine":74,"keywordType":"Context","textWithKeyword":"And I enter the email \"gangadhar@blazeautomation.com\"","stepMatchArguments":[{"group":{"start":18,"value":"\"gangadhar@blazeautomation.com\"","children":[{"start":19,"value":"gangadhar@blazeautomation.com","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":150,"gherkinStepLine":75,"keywordType":"Context","textWithKeyword":"And Click on submit button","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":76,"keywordType":"Context","textWithKeyword":"And I enter the password \"123fthu\"","stepMatchArguments":[{"group":{"start":21,"value":"\"123fthu\"","children":[{"start":22,"value":"123fthu","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":152,"gherkinStepLine":77,"keywordType":"Action","textWithKeyword":"When Click on the Submit button","stepMatchArguments":[]},{"pwStepLine":153,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"Then I should see an error message indicating \"Wrong password. Try again or click Forgot password to reset it.\"","stepMatchArguments":[{"group":{"start":41,"value":"\"Wrong password. Try again or click Forgot password to reset it.\"","children":[{"start":42,"value":"Wrong password. Try again or click Forgot password to reset it.","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end